---
title: "iTRAQI_index_visualisations"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: rmarkdown::github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# library(raster)
# library(sp)
# library(gstat)
library(tidyverse)
# library(sf)
# library(rnaturalearth)
# library(ggspatial)
# library(progress)
library(leaflet)
library(leaflet.extras)
```


```{r}
layers_dir <- "output/layers"

rehab_raster <- readRDS(file.path(layers_dir, "rehab_raster.rds"))
acute_raster <- readRDS(file.path(layers_dir, "acute_raster.rds"))
rehab_gold_raster <- readRDS(file.path(layers_dir, "rehab_raster_gold.rds"))


rehab_and_acute_raster <- rehab_raster + acute_raster
rehab_gold_and_silver <- rehab_raster + rehab_gold_raster

```


```{r}
palNum1 <- colorNumeric(c("#FFFFCC", "#FFEDA0"), domain=0:30, na.color="transparent")
  palNum2 <- colorNumeric(c("#FFEDA0", "#FED976"), domain=30:60, na.color="transparent")
  palNum3 <- colorNumeric(c("#FED976", "#FEB24C"), domain=60:120, na.color="transparent")
  palNum4 <- colorNumeric(c("#FEB24C", "#FD8D3C"), domain=120:180, na.color="transparent")
  palNum5 <- colorNumeric(c("#FD8D3C", "#FC4E2A"), domain=180:240, na.color="transparent")
  palNum6 <- colorNumeric(c("#FC4E2A", "#E31A1C"), domain=240:300, na.color="transparent")
  palNum7 <- colorNumeric(c("#E31A1C", "#B10026"), domain=300:360, na.color="transparent")
  palNum8 <- colorNumeric(c("#B10026", "#000000"), domain=360:900, na.color="transparent")
  
palNum <- function(x){
  case_when(
    x < 30 ~ palNum1(x),
    x < 60 ~ palNum2(x),
    x < 120 ~ palNum3(x),
    x < 180 ~ palNum4(x),
    x < 240 ~ palNum5(x),
    x < 300 ~ palNum6(x),
    x < 360 ~ palNum7(x),
    x < 900 ~ palNum8(x),
    x >= 900 ~ "#000000",
    TRUE ~ "transparent"
  )
}

palNum_hours <- function(x){
  palNum(x*60)
}


leaflet() %>% 
  addProviderTiles("Esri") %>%
  addMapPane(name = "layers", zIndex = 200) %>%
  addRasterImage(
    x=raster::raster(rehab_and_acute_raster, layer=1),
    colors=palNum,
    group="acute + rehab (silver)",
    options=leafletOptions(pane="layers")
  ) %>%
  addRasterImage(
    x=raster::raster(rehab_gold_and_silver, layer=1),
    colors=palNum,
    group="gold + silver",
    options=leafletOptions(pane="layers")
  ) %>%
  addRasterImage(
    x=raster::raster(acute_raster, layer=1),
    colors=palNum,
    group="acute",
    options=leafletOptions(pane="layers")
  ) %>%
  addRasterImage(
    x=raster::raster(rehab_raster, layer=1),
    colors=palNum,
    group="rehab",
    options=leafletOptions(pane="layers")
  ) %>%
  addLayersControl(
    position = "topright",
    baseGroups = c("None","acute + rehab (silver)","gold + silver", "acute", "rehab"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>% 
  leaflegend::addLegendNumeric(
    pal=palNum_hours,
    position="topright",
    height=250,
    width=24,
    bins=10,
    value=c(-0.01, 0:20, 20.1),
    title="Time to care (hours)"
  )

```