---
title: "iTRAQI"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sp)
library(gstat)
library(tidyverse)
library(sf)
library(rnaturalearth)
library(ggspatial)
```

#### resources used:
* kriging (https://rpubs.com/nabilabd/118172)







# load inputs
```{r}

df_times <- read.csv("../drive_times/QLD_locations_with_RSQ_times_20220210.csv")
coordinates(df_times) <- ~ x + y

qld_bounary <- st_read("input/qld_state_polygon_shp/QLD_STATE_POLYGON_shp.shp")

qld_SAs <- st_read("input/qld_sa_zones/MB_2016_QLD.shp")

ggplot(data = world) +
  geom_sf() +
  geom_sf(data=qld_SAs, aes(color=SA2_MAIN16)) +
  coord_sf(xlim = c(100.00, 160.00), ylim = c(-45.00, -10.00), expand = T) 
```

# base map and points
```{r}

world <- ne_countries(scale = "medium", returnclass = "sf")
ggplot(data = world) +
  geom_sf() +
  geom_sf(data=qld_bounary, color="blue") +
  labs( x = "Longitude", y = "Latitude") +
  coord_sf(xlim = c(100.00, 160.00), ylim = c(-45.00, -10.00), expand = T) +
  annotation_scale(location = "bl", width_hint = 0.5) +
  annotation_north_arrow(location = "bl", which_north = "true", 
                         pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"),
                         style = north_arrow_fancy_orienteering) +
  geom_point(data=as.data.frame(df_times), aes(x,y))

```

# kriging - select variogram model (Gaussian looks best)
```{r}
lzn_vgm <- variogram(acute_time~1, df_times)
lzn_fit <- fit.variogram(lzn_vgm, model=vgm("Gau"))

plot(lzn_vgm, lzn_fit)
# show.vgms()
```

# kriging - create spatial domain to interpolate over
```{r}
map = read_sf("input/qld_state_polygon_shp/QLD_STATE_POLYGON_shp.shp")

pnts_sf <- st_as_sf(grid, coords = c('x1', 'x2'), crs = st_crs(map))

pnts <- pnts_sf %>% mutate(
  intersection = as.integer(st_intersects(geometry, map))
) %>%
  filter(!is.na(intersection)) %>%
  st_coordinates() %>% 
  as.data.frame()
coordinates(pnts) <- ~ X + Y

```

# kriging - generate interpolations
```{r}

lzn_kriged <- krige(acute_time ~ 1, df_times, pnts, model=lzn_fit)%>%
  as.data.frame

lzn_kriged  %>%
  ggplot(aes(X, Y)) + 
  geom_tile(aes(fill=var1.pred)) + 
  coord_equal()+
  scale_fill_gradient(low = "yellow", high="red")

```

# add interpolation layer to map
```{r}
ggplot(data = world) +
  geom_sf() +
  geom_sf(data=qld_bounary, color="blue") +
  labs( x = "Longitude", y = "Latitude") +
  coord_sf(xlim = c(100.00, 160.00), ylim = c(-45.00, -10.00), expand = T) +
  annotation_scale(location = "bl", width_hint = 0.5) +
  geom_tile(data=lzn_kriged, aes(X, Y, fill=var1.pred)) +
  geom_point(data=as.data.frame(df_times), aes(x,y)) +
  scale_fill_gradient(low = "yellow", high="red")

```


# spatial join from SA1 and SA2 polygons to interpolated values